exchange-rate-api:
  base-url: https://v6.exchangerate-api.com/v6/
  api-key: random-api-key
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect